# All excutables/targets to be generated
all: variables height calculator bartender

# Compilation instructions
variables: variables.cpp
	g++ variables.cpp -o variables

height: height.cpp
	g++ height.cpp -o height

calculator: calculator.cpp
	g++ calculator.cpp -o calculator

bartender: bartender.cpp
	g++ bartender.cpp -o bartender

# Clean instruction
clean: 
	rm variables height calculator bartender